version: '3.8'

services:
  # Redis para cache
  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  # MinIO (alternativa ao Cloudinary para armazenamento de mídia)
  minio:
    image: minio/minio
    ports:
      - "9010:9000"
      - "9011:9001"
    environment:
      MINIO_ROOT_USER: templatesia
      MINIO_ROOT_PASSWORD: templatesia123
    volumes:
      - minio_data:/data
    command: server --console-address ":9001" /data

  # Graylog (alternativa ao Sentry para logs)
  mongo-graylog:
    image: mongo:4.2
    volumes:
      - mongo_graylog_data:/data/db

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch-oss:7.10.2
    environment:
      - http.host=0.0.0.0
      - transport.host=localhost
      - network.host=0.0.0.0
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    volumes:
      - elasticsearch_data:/usr/share/elasticsearch/data

  graylog:
    image: graylog/graylog:4.3
    ports:
      - "9100:9000"
      - "12201:12201/udp"
      - "1514:1514"
    environment:
      - GRAYLOG_PASSWORD_SECRET=templatesia123
      - GRAYLOG_ROOT_PASSWORD_SHA2=8c6976e5b5410415bde908bd4dee15dfb167a9c873fc4bb8a81f6f2ab448a918
      - GRAYLOG_HTTP_EXTERNAL_URI=http://localhost:9100/
    depends_on:
      - mongo-graylog
      - elasticsearch
    volumes:
      - graylog_data:/usr/share/graylog/data

volumes:
  redis_data:
  minio_data:
  mongo_graylog_data:
  elasticsearch_data:
  graylog_data:
