name: Análise de Segurança

on:
  workflow_dispatch:
    inputs:
      scan_type:
        description: 'Tipo de análise de segurança'
        required: true
        default: 'full'
        type: choice
        options:
          - full
          - dependencies
          - code
  push:
    tags:
      - 'security-*'
      - 'release-*'
  schedule:
    - cron: '0 0 * * 0'  # Mantém o scan semanal por segurança

jobs:
  security:
    name: Verificações de Segurança
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          
      - name: Install dependencies
        run: npm ci
        
      - name: Run OWASP Dependency Check
        if: github.event.inputs.scan_type == 'full' || github.event.inputs.scan_type == 'dependencies'
        uses: dependency-check/Dependency-Check_Action@main
        with:
          project: 'templatesia'
          path: '.'
          format: 'HTML'
          
      - name: Run Snyk to check for vulnerabilities
        if: github.event.inputs.scan_type == 'full' || github.event.inputs.scan_type == 'dependencies'
        uses: snyk/actions/node@master
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
          
      - name: Upload security scan results
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: reports/dependency-check-report.sarif
          
  codeql:
    name: CodeQL Analysis
    runs-on: ubuntu-latest
    if: github.event.inputs.scan_type == 'full' || github.event.inputs.scan_type == 'code'
    permissions:
      security-events: write
      actions: read
      contents: read
    steps:
      - uses: actions/checkout@v4
      
      - name: Initialize CodeQL
        uses: github/codeql-action/init@v2
        with:
          languages: javascript, typescript
          
      - name: Perform CodeQL Analysis
        uses: github/codeql-action/analyze@v2 